### ISSUE TITLE
line endings

### ISSUE THREAD

**Issue by nemesis7331** [NullArray/SysEnum#1]
You need to re-save the file using Unix line endings, else you get this error:
`-bash: ./SysEnum.sh: /bin/bash^M: bad interpreter: No such file or directory`

**Comment by NullArray** [comment]
Sorry for the late reply, i have been quite busy. Thank you for mentioning the issue.

**Comment by NullArray** [comment]
Fixed this by rewriting the entire thing. Enjoy.
